// =======================================================================================================
// ZHRXXgroup Project 🚀 - samba Build System (samba.h)
// File: SambaProject.c
// Author(s): ZHRXXgroup
// Version: 1
// Free to use, modify, and share under our Open Source License (src.zhrxxgroup.com/OPENSOURCE_LICENSE).
// Want to contribute? Visit: issues.zhrxxgroup.com
// GitHub: https://github.com/ZHRXXgroup/samba.h
// ========================================================================================================

#include <stdio.h>

int main() {
    FILE *fp;

    fp = fopen("samba.c", "w");

    fprintf(fp, "///////////////////////////////\n");
    fprintf(fp, "// GENERATED BY SambaProject //\n");
    fprintf(fp, "///////////////////////////////\n");

    fprintf(fp, "\n// Automatic sets verbose_mode to true: #define S_VERBOSE_MODE\n");
    fprintf(fp, "// uses ccache with compiler: #define S_CACHE_COMPILATION\n");
    fprintf(fp, "#define S_DEBUG_MODE\n");
    fprintf(fp, "// if you wanna make a optimized executable: #define S_RELEASE_MODE\n");
    fprintf(fp, "// if you wanna us clang: #define S_CMP_CLANG\n");
    fprintf(fp, "#include \"samba.h\"\n");
    fprintf(fp, "#include <stdlib.h>\n");
    fprintf(fp, "#include <stdio.h>\n");
    fprintf(fp, "#include <stdbool.h>\n");
    fprintf(fp, "\n");
    fprintf(fp, "int main() {\n");
    fprintf(fp, "    initialize_build_flags();\n");
    fprintf(fp, "    compile(\"src_file.c\", \"your_output\", false); // 3 arg is to make it shared lib\n");
    fprintf(fp, "\n");
    fprintf(fp, "    SAMBA_GO_REBUILD_URSELF();\n");
    fprintf(fp, "\n");
    fprintf(fp, "    free_all();\n");
    fprintf(fp, "\n");
    fprintf(fp, "    return EXIT_SUCCESS;\n");
    fprintf(fp, "}\n");

    fclose(fp);
}
