#include <stdio.h>

int main() {
    FILE *fp;

    fp = fopen("samba.c", "w");

    fprintf(fp, "///////////////////////////////\n");
    fprintf(fp, "// GENERATED BY SambaProject //\n");
    fprintf(fp, "///////////////////////////////\n");

    fprintf(fp, "\n// Automatic sets verbose_mode to true: #define S_VERBOSE_MODE\n");
    fprintf(fp, "// uses ccache with compiler: #define S_CACHE_COMPILATION\n");
    fprintf(fp, "#define S_DEBUG_MODE\n");
    fprintf(fp, "// if you wanna make a optimized executable: #define S_RELEASE_MODE\n");
    fprintf(fp, "// if you wanna us clang: #define S_CMP_CLANG\n");
    fprintf(fp, "#include \"samba.h\"\n");
    fprintf(fp, "#include <stdlib.h>\n");
    fprintf(fp, "#include <stdio.h>\n");
    fprintf(fp, "#include <stdbool.h>\n");
    fprintf(fp, "\n");
    fprintf(fp, "int main() {\n");
    fprintf(fp, "    initialize_build_flags();\n");
    fprintf(fp, "    compile(\"src_file.c\", \"your_output\", false); // 3 arg is to make it shared lib\n");
    fprintf(fp, "\n");
    fprintf(fp, "    SAMBA_GO_REBUILD_URSELF();\n");
    fprintf(fp, "\n");
    fprintf(fp, "    free_all();\n");
    fprintf(fp, "\n");
    fprintf(fp, "    return EXIT_SUCCESS;\n");
    fprintf(fp, "}\n");

    fclose(fp);
}
